theme: jekyll-theme-hacker
title: Kitchen Duties 
locale: en_BE

owner:
  name: JUNG Frederic
  avatar: bio-photo.jpg
  bio: "PHD researcher in Oncogenetics"
  email: frederic.jung@uantwerpen.be
  github: FredCoddy
